environment:
  access_token:
   secure: wShbQfYcfaf2ZgU8dFgLTVJglCyGiK9/BHWcEbVZ4sU8SqxokPc4pFfl1ZY4qtlO

before_build:
  - ps: Install-Product node stable
  - npm install
  
# Post-install test scripts.
test_script:
  - node --version
  - npm --version

build_script: 
 - npm run lint

skip_commits:
  # Regex for matching commit message
  message: /Automated Appveyor build/
  # Commit author's username, name, email or regexp maching one of these.
  author: Appveyor Automated Build

# Note: AppVeyor checkout only the last commit and not the entire branch. So you may have to checkout the wanted branch: git checkout master
on_success:
 #- cmd: SET PATH=%tempath%
 - git config --global credential.helper store
 - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
 - git config --global user.email "app@veyor.mp4"
 - git config --global user.name "Appveyor Automated Build"
 - cmd: For /f "tokens=2-4 delims=/ " %%a in ('date /t') do (set mydate=%%c-%%a-%%b)
 - cmd: For /f "tokens=1-2 delims=/:" %%a in ('time /t') do (set mytime=%%a:%%b)
# update gh-pages with master's contents
 - git checkout gh-pages || git checkout -b gh-pages
 - git status
 - git rm build/src/libraries/beautifier.js
 - git reset --hard HEAD
 - git rebase master
 - git push origin gh-pages
