version: '2'
plugins:
  duplication: #seems to be working
    enabled: false
    config:
      languages:
      - javascript
  fixme: #seems to be working
    enabled: false #eslint already does this
    config:
      strings:
      - FIXME
      - XXX
      - TODO
      - todo
  eslint: #no idea if needs config https://docs.codeclimate.com/docs/eslint
    enabled: true
    channel: 'eslint-3'
    config:
      config: ./.eslintrc.json
      extensions:
      - .es6
      - .js
      - .user.js
      - .jsx
  csslint: #seems to be working
    enabled: false #it's shit!
  shellcheck:
    enabled: true
  markdownlint:
    enabled: false

exclude_patterns:
- '**.min.js'
- '**/*.min.js'
- '*.min.js'

checks:
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
